'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("ATIDAQFTDemoOptions"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class ATIDAQFTDemoOptions
    Inherits Global.System.Data.DataSet
    
    Private tableDemoOptions As DemoOptionsDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("DemoOptions")) Is Nothing) Then
                MyBase.Tables.Add(New DemoOptionsDataTable(ds.Tables("DemoOptions")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property DemoOptions() As DemoOptionsDataTable
        Get
            Return Me.tableDemoOptions
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As ATIDAQFTDemoOptions = CType(MyBase.Clone,ATIDAQFTDemoOptions)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXml(reader)
            If (Not (ds.Tables("DemoOptions")) Is Nothing) Then
                MyBase.Tables.Add(New DemoOptionsDataTable(ds.Tables("DemoOptions")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableDemoOptions = CType(MyBase.Tables("DemoOptions"),DemoOptionsDataTable)
        If (initTable = true) Then
            If (Not (Me.tableDemoOptions) Is Nothing) Then
                Me.tableDemoOptions.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Sub InitClass()
        Me.DataSetName = "ATIDAQFTDemoOptions"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/ATIDAQFTDemoOptions.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableDemoOptions = New DemoOptionsDataTable()
        MyBase.Tables.Add(Me.tableDemoOptions)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Function ShouldSerializeDemoOptions() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As ATIDAQFTDemoOptions = New ATIDAQFTDemoOptions()
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Delegate Sub DemoOptionsRowChangeEventHandler(ByVal sender As Object, ByVal e As DemoOptionsRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class DemoOptionsDataTable
        Inherits Global.System.Data.TypedTableBase(Of DemoOptionsRow)
        
        Private columnCalibrationFile As Global.System.Data.DataColumn
        
        Private columnDAQDeviceName As Global.System.Data.DataColumn
        
        Private columnDAQSampleRate As Global.System.Data.DataColumn
        
        Private columnAveraging As Global.System.Data.DataColumn
        
        Private columnDAQFirstChannel As Global.System.Data.DataColumn
        
        Private columnUseThermistor As Global.System.Data.DataColumn
        
        Private columnBufferSize As Global.System.Data.DataColumn
        
        Private columnForceUnits As Global.System.Data.DataColumn
        
        Private columnTorqueUnits As Global.System.Data.DataColumn
        
        Private columnDiagnosticSampleRate As Global.System.Data.DataColumn
        
        Private columnDiagnosticSampleSize As Global.System.Data.DataColumn
        
        Private columnDiagnosticAveraging As Global.System.Data.DataColumn
        
        Private columnXDisplacement As Global.System.Data.DataColumn
        
        Private columnYDisplacement As Global.System.Data.DataColumn
        
        Private columnZDisplacement As Global.System.Data.DataColumn
        
        Private columnXRotation As Global.System.Data.DataColumn
        
        Private columnYRotation As Global.System.Data.DataColumn
        
        Private columnZRotation As Global.System.Data.DataColumn
        
        Private columnDisplacementUnits As Global.System.Data.DataColumn
        
        Private columnRotationUnits As Global.System.Data.DataColumn
        
        Private columnFirstTimeRunning As Global.System.Data.DataColumn
        
        Private columnDiagnosticUseThermistor As Global.System.Data.DataColumn
        
        Private columnConnectionMode As Global.System.Data.DataColumn
        
        Private columnPresentationIconFile As Global.System.Data.DataColumn
        
        Private columnPresentationTitle As Global.System.Data.DataColumn
        
        Private columnPresentationHeading As Global.System.Data.DataColumn
        
        Private columnPresentationBannerFile As Global.System.Data.DataColumn
        
        Private columnAutoScaleHistory As Global.System.Data.DataColumn
        
        Private columnHistoryViewMode As Global.System.Data.DataColumn
        
        Private columnHistoryDuration As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "DemoOptions"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CalibrationFileColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCalibrationFile
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DAQDeviceNameColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDAQDeviceName
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DAQSampleRateColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDAQSampleRate
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property AveragingColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAveraging
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DAQFirstChannelColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDAQFirstChannel
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property UseThermistorColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnUseThermistor
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property BufferSizeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnBufferSize
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ForceUnitsColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnForceUnits
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property TorqueUnitsColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTorqueUnits
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DiagnosticSampleRateColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDiagnosticSampleRate
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DiagnosticSampleSizeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDiagnosticSampleSize
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DiagnosticAveragingColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDiagnosticAveraging
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property XDisplacementColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnXDisplacement
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property YDisplacementColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnYDisplacement
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ZDisplacementColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnZDisplacement
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property XRotationColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnXRotation
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property YRotationColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnYRotation
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ZRotationColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnZRotation
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DisplacementUnitsColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDisplacementUnits
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property RotationUnitsColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnRotationUnits
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property FirstTimeRunningColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnFirstTimeRunning
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DiagnosticUseThermistorColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDiagnosticUseThermistor
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ConnectionModeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnConnectionMode
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PresentationIconFileColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPresentationIconFile
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PresentationTitleColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPresentationTitle
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PresentationHeadingColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPresentationHeading
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PresentationBannerFileColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPresentationBannerFile
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property AutoScaleHistoryColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAutoScaleHistory
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property HistoryViewModeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnHistoryViewMode
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property HistoryDurationColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnHistoryDuration
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As DemoOptionsRow
            Get
                Return CType(Me.Rows(index),DemoOptionsRow)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event DemoOptionsRowChanging As DemoOptionsRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event DemoOptionsRowChanged As DemoOptionsRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event DemoOptionsRowDeleting As DemoOptionsRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event DemoOptionsRowDeleted As DemoOptionsRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Sub AddDemoOptionsRow(ByVal row As DemoOptionsRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Function AddDemoOptionsRow( _
                    ByVal CalibrationFile As String,  _
                    ByVal DAQDeviceName As String,  _
                    ByVal DAQSampleRate As Double,  _
                    ByVal Averaging As Long,  _
                    ByVal DAQFirstChannel As Long,  _
                    ByVal UseThermistor As Boolean,  _
                    ByVal BufferSize As Long,  _
                    ByVal ForceUnits As String,  _
                    ByVal TorqueUnits As String,  _
                    ByVal DiagnosticSampleRate As Double,  _
                    ByVal DiagnosticSampleSize As Long,  _
                    ByVal DiagnosticAveraging As Long,  _
                    ByVal XDisplacement As Double,  _
                    ByVal YDisplacement As Double,  _
                    ByVal ZDisplacement As Double,  _
                    ByVal XRotation As Double,  _
                    ByVal YRotation As Double,  _
                    ByVal ZRotation As Double,  _
                    ByVal DisplacementUnits As String,  _
                    ByVal RotationUnits As String,  _
                    ByVal FirstTimeRunning As Boolean,  _
                    ByVal DiagnosticUseThermistor As Boolean,  _
                    ByVal ConnectionMode As String,  _
                    ByVal PresentationIconFile As String,  _
                    ByVal PresentationTitle As String,  _
                    ByVal PresentationHeading As String,  _
                    ByVal PresentationBannerFile As String,  _
                    ByVal AutoScaleHistory As Boolean,  _
                    ByVal HistoryViewMode As Boolean,  _
                    ByVal HistoryDuration As String) As DemoOptionsRow
            Dim rowDemoOptionsRow As DemoOptionsRow = CType(Me.NewRow,DemoOptionsRow)
            Dim columnValuesArray() As Object = New Object() {CalibrationFile, DAQDeviceName, DAQSampleRate, Averaging, DAQFirstChannel, UseThermistor, BufferSize, ForceUnits, TorqueUnits, DiagnosticSampleRate, DiagnosticSampleSize, DiagnosticAveraging, XDisplacement, YDisplacement, ZDisplacement, XRotation, YRotation, ZRotation, DisplacementUnits, RotationUnits, FirstTimeRunning, DiagnosticUseThermistor, ConnectionMode, PresentationIconFile, PresentationTitle, PresentationHeading, PresentationBannerFile, AutoScaleHistory, HistoryViewMode, HistoryDuration}
            rowDemoOptionsRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowDemoOptionsRow)
            Return rowDemoOptionsRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As DemoOptionsDataTable = CType(MyBase.Clone,DemoOptionsDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New DemoOptionsDataTable()
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub InitVars()
            Me.columnCalibrationFile = MyBase.Columns("CalibrationFile")
            Me.columnDAQDeviceName = MyBase.Columns("DAQDeviceName")
            Me.columnDAQSampleRate = MyBase.Columns("DAQSampleRate")
            Me.columnAveraging = MyBase.Columns("Averaging")
            Me.columnDAQFirstChannel = MyBase.Columns("DAQFirstChannel")
            Me.columnUseThermistor = MyBase.Columns("UseThermistor")
            Me.columnBufferSize = MyBase.Columns("BufferSize")
            Me.columnForceUnits = MyBase.Columns("ForceUnits")
            Me.columnTorqueUnits = MyBase.Columns("TorqueUnits")
            Me.columnDiagnosticSampleRate = MyBase.Columns("DiagnosticSampleRate")
            Me.columnDiagnosticSampleSize = MyBase.Columns("DiagnosticSampleSize")
            Me.columnDiagnosticAveraging = MyBase.Columns("DiagnosticAveraging")
            Me.columnXDisplacement = MyBase.Columns("XDisplacement")
            Me.columnYDisplacement = MyBase.Columns("YDisplacement")
            Me.columnZDisplacement = MyBase.Columns("ZDisplacement")
            Me.columnXRotation = MyBase.Columns("XRotation")
            Me.columnYRotation = MyBase.Columns("YRotation")
            Me.columnZRotation = MyBase.Columns("ZRotation")
            Me.columnDisplacementUnits = MyBase.Columns("DisplacementUnits")
            Me.columnRotationUnits = MyBase.Columns("RotationUnits")
            Me.columnFirstTimeRunning = MyBase.Columns("FirstTimeRunning")
            Me.columnDiagnosticUseThermistor = MyBase.Columns("DiagnosticUseThermistor")
            Me.columnConnectionMode = MyBase.Columns("ConnectionMode")
            Me.columnPresentationIconFile = MyBase.Columns("PresentationIconFile")
            Me.columnPresentationTitle = MyBase.Columns("PresentationTitle")
            Me.columnPresentationHeading = MyBase.Columns("PresentationHeading")
            Me.columnPresentationBannerFile = MyBase.Columns("PresentationBannerFile")
            Me.columnAutoScaleHistory = MyBase.Columns("AutoScaleHistory")
            Me.columnHistoryViewMode = MyBase.Columns("HistoryViewMode")
            Me.columnHistoryDuration = MyBase.Columns("HistoryDuration")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Private Sub InitClass()
            Me.columnCalibrationFile = New Global.System.Data.DataColumn("CalibrationFile", GetType(String), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnCalibrationFile)
            Me.columnDAQDeviceName = New Global.System.Data.DataColumn("DAQDeviceName", GetType(String), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnDAQDeviceName)
            Me.columnDAQSampleRate = New Global.System.Data.DataColumn("DAQSampleRate", GetType(Double), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnDAQSampleRate)
            Me.columnAveraging = New Global.System.Data.DataColumn("Averaging", GetType(Long), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnAveraging)
            Me.columnDAQFirstChannel = New Global.System.Data.DataColumn("DAQFirstChannel", GetType(Long), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnDAQFirstChannel)
            Me.columnUseThermistor = New Global.System.Data.DataColumn("UseThermistor", GetType(Boolean), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnUseThermistor)
            Me.columnBufferSize = New Global.System.Data.DataColumn("BufferSize", GetType(Long), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnBufferSize)
            Me.columnForceUnits = New Global.System.Data.DataColumn("ForceUnits", GetType(String), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnForceUnits)
            Me.columnTorqueUnits = New Global.System.Data.DataColumn("TorqueUnits", GetType(String), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnTorqueUnits)
            Me.columnDiagnosticSampleRate = New Global.System.Data.DataColumn("DiagnosticSampleRate", GetType(Double), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnDiagnosticSampleRate)
            Me.columnDiagnosticSampleSize = New Global.System.Data.DataColumn("DiagnosticSampleSize", GetType(Long), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnDiagnosticSampleSize)
            Me.columnDiagnosticAveraging = New Global.System.Data.DataColumn("DiagnosticAveraging", GetType(Long), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnDiagnosticAveraging)
            Me.columnXDisplacement = New Global.System.Data.DataColumn("XDisplacement", GetType(Double), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnXDisplacement)
            Me.columnYDisplacement = New Global.System.Data.DataColumn("YDisplacement", GetType(Double), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnYDisplacement)
            Me.columnZDisplacement = New Global.System.Data.DataColumn("ZDisplacement", GetType(Double), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnZDisplacement)
            Me.columnXRotation = New Global.System.Data.DataColumn("XRotation", GetType(Double), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnXRotation)
            Me.columnYRotation = New Global.System.Data.DataColumn("YRotation", GetType(Double), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnYRotation)
            Me.columnZRotation = New Global.System.Data.DataColumn("ZRotation", GetType(Double), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnZRotation)
            Me.columnDisplacementUnits = New Global.System.Data.DataColumn("DisplacementUnits", GetType(String), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnDisplacementUnits)
            Me.columnRotationUnits = New Global.System.Data.DataColumn("RotationUnits", GetType(String), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnRotationUnits)
            Me.columnFirstTimeRunning = New Global.System.Data.DataColumn("FirstTimeRunning", GetType(Boolean), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnFirstTimeRunning)
            Me.columnDiagnosticUseThermistor = New Global.System.Data.DataColumn("DiagnosticUseThermistor", GetType(Boolean), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnDiagnosticUseThermistor)
            Me.columnConnectionMode = New Global.System.Data.DataColumn("ConnectionMode", GetType(String), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnConnectionMode)
            Me.columnPresentationIconFile = New Global.System.Data.DataColumn("PresentationIconFile", GetType(String), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnPresentationIconFile)
            Me.columnPresentationTitle = New Global.System.Data.DataColumn("PresentationTitle", GetType(String), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnPresentationTitle)
            Me.columnPresentationHeading = New Global.System.Data.DataColumn("PresentationHeading", GetType(String), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnPresentationHeading)
            Me.columnPresentationBannerFile = New Global.System.Data.DataColumn("PresentationBannerFile", GetType(String), Nothing, Global.System.Data.MappingType.Attribute)
            MyBase.Columns.Add(Me.columnPresentationBannerFile)
            Me.columnAutoScaleHistory = New Global.System.Data.DataColumn("AutoScaleHistory", GetType(Boolean), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAutoScaleHistory)
            Me.columnHistoryViewMode = New Global.System.Data.DataColumn("HistoryViewMode", GetType(Boolean), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnHistoryViewMode)
            Me.columnHistoryDuration = New Global.System.Data.DataColumn("HistoryDuration", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnHistoryDuration)
            Me.columnCalibrationFile.Namespace = ""
            Me.columnCalibrationFile.DefaultValue = CType("",String)
            Me.columnDAQDeviceName.Namespace = ""
            Me.columnDAQDeviceName.DefaultValue = CType("dev1",String)
            Me.columnDAQSampleRate.Namespace = ""
            Me.columnDAQSampleRate.DefaultValue = CType(1000R,Double)
            Me.columnAveraging.Namespace = ""
            Me.columnAveraging.DefaultValue = CType(16,Long)
            Me.columnDAQFirstChannel.Namespace = ""
            Me.columnDAQFirstChannel.DefaultValue = CType(0,Long)
            Me.columnUseThermistor.Namespace = ""
            Me.columnUseThermistor.DefaultValue = CType(true,Boolean)
            Me.columnBufferSize.Namespace = ""
            Me.columnBufferSize.DefaultValue = CType(500,Long)
            Me.columnForceUnits.Namespace = ""
            Me.columnTorqueUnits.Namespace = ""
            Me.columnDiagnosticSampleRate.Namespace = ""
            Me.columnDiagnosticSampleRate.DefaultValue = CType(1000R,Double)
            Me.columnDiagnosticSampleSize.Namespace = ""
            Me.columnDiagnosticSampleSize.DefaultValue = CType(1000,Long)
            Me.columnDiagnosticAveraging.Namespace = ""
            Me.columnDiagnosticAveraging.DefaultValue = CType(1,Long)
            Me.columnXDisplacement.Namespace = ""
            Me.columnYDisplacement.Namespace = ""
            Me.columnZDisplacement.Namespace = ""
            Me.columnXRotation.Namespace = ""
            Me.columnYRotation.Namespace = ""
            Me.columnZRotation.Namespace = ""
            Me.columnDisplacementUnits.Namespace = ""
            Me.columnRotationUnits.Namespace = ""
            Me.columnFirstTimeRunning.Namespace = ""
            Me.columnDiagnosticUseThermistor.Namespace = ""
            Me.columnConnectionMode.Namespace = ""
            Me.columnPresentationIconFile.Namespace = ""
            Me.columnPresentationIconFile.DefaultValue = CType("ATI1.ico",String)
            Me.columnPresentationTitle.Namespace = ""
            Me.columnPresentationTitle.DefaultValue = CType("ATI F/T Visualizer",String)
            Me.columnPresentationHeading.Namespace = ""
            Me.columnPresentationHeading.DefaultValue = CType("ATI Industrial Automation - Force/Torque Sensors",String)
            Me.columnPresentationBannerFile.Namespace = ""
            Me.columnPresentationBannerFile.DefaultValue = CType("ATI logo_4c_w_tag.JPG",String)
            Me.columnHistoryDuration.DefaultValue = CType("10",String)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function NewDemoOptionsRow() As DemoOptionsRow
            Return CType(Me.NewRow,DemoOptionsRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New DemoOptionsRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(DemoOptionsRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.DemoOptionsRowChangedEvent) Is Nothing) Then
                RaiseEvent DemoOptionsRowChanged(Me, New DemoOptionsRowChangeEvent(CType(e.Row,DemoOptionsRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.DemoOptionsRowChangingEvent) Is Nothing) Then
                RaiseEvent DemoOptionsRowChanging(Me, New DemoOptionsRowChangeEvent(CType(e.Row,DemoOptionsRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.DemoOptionsRowDeletedEvent) Is Nothing) Then
                RaiseEvent DemoOptionsRowDeleted(Me, New DemoOptionsRowChangeEvent(CType(e.Row,DemoOptionsRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.DemoOptionsRowDeletingEvent) Is Nothing) Then
                RaiseEvent DemoOptionsRowDeleting(Me, New DemoOptionsRowChangeEvent(CType(e.Row,DemoOptionsRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub RemoveDemoOptionsRow(ByVal row As DemoOptionsRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
            Dim ds As ATIDAQFTDemoOptions = New ATIDAQFTDemoOptions()
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "DemoOptionsDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    Partial Public Class DemoOptionsRow
        Inherits Global.System.Data.DataRow
        
        Private tableDemoOptions As DemoOptionsDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableDemoOptions = CType(Me.Table,DemoOptionsDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CalibrationFile() As String
            Get
                If Me.IsCalibrationFileNull Then
                    Return ""
                Else
                    Return CType(Me(Me.tableDemoOptions.CalibrationFileColumn),String)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.CalibrationFileColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DAQDeviceName() As String
            Get
                If Me.IsDAQDeviceNameNull Then
                    Return "dev1"
                Else
                    Return CType(Me(Me.tableDemoOptions.DAQDeviceNameColumn),String)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.DAQDeviceNameColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DAQSampleRate() As Double
            Get
                If Me.IsDAQSampleRateNull Then
                    Return 1000R
                Else
                    Return CType(Me(Me.tableDemoOptions.DAQSampleRateColumn),Double)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.DAQSampleRateColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property Averaging() As Long
            Get
                If Me.IsAveragingNull Then
                    Return 16
                Else
                    Return CType(Me(Me.tableDemoOptions.AveragingColumn),Long)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.AveragingColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DAQFirstChannel() As Long
            Get
                If Me.IsDAQFirstChannelNull Then
                    Return 0
                Else
                    Return CType(Me(Me.tableDemoOptions.DAQFirstChannelColumn),Long)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.DAQFirstChannelColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property UseThermistor() As Boolean
            Get
                If Me.IsUseThermistorNull Then
                    Return true
                Else
                    Return CType(Me(Me.tableDemoOptions.UseThermistorColumn),Boolean)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.UseThermistorColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property BufferSize() As Long
            Get
                If Me.IsBufferSizeNull Then
                    Return 500
                Else
                    Return CType(Me(Me.tableDemoOptions.BufferSizeColumn),Long)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.BufferSizeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ForceUnits() As String
            Get
                Try 
                    Return CType(Me(Me.tableDemoOptions.ForceUnitsColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ForceUnits' in table 'DemoOptions' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDemoOptions.ForceUnitsColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property TorqueUnits() As String
            Get
                Try 
                    Return CType(Me(Me.tableDemoOptions.TorqueUnitsColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TorqueUnits' in table 'DemoOptions' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDemoOptions.TorqueUnitsColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DiagnosticSampleRate() As Double
            Get
                If Me.IsDiagnosticSampleRateNull Then
                    Return 1000R
                Else
                    Return CType(Me(Me.tableDemoOptions.DiagnosticSampleRateColumn),Double)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.DiagnosticSampleRateColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DiagnosticSampleSize() As Long
            Get
                If Me.IsDiagnosticSampleSizeNull Then
                    Return 1000
                Else
                    Return CType(Me(Me.tableDemoOptions.DiagnosticSampleSizeColumn),Long)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.DiagnosticSampleSizeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DiagnosticAveraging() As Long
            Get
                If Me.IsDiagnosticAveragingNull Then
                    Return 1
                Else
                    Return CType(Me(Me.tableDemoOptions.DiagnosticAveragingColumn),Long)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.DiagnosticAveragingColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property XDisplacement() As Double
            Get
                If Me.IsXDisplacementNull Then
                    Return 0R
                Else
                    Return CType(Me(Me.tableDemoOptions.XDisplacementColumn),Double)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.XDisplacementColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property YDisplacement() As Double
            Get
                If Me.IsYDisplacementNull Then
                    Return 0R
                Else
                    Return CType(Me(Me.tableDemoOptions.YDisplacementColumn),Double)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.YDisplacementColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ZDisplacement() As Double
            Get
                If Me.IsZDisplacementNull Then
                    Return 0R
                Else
                    Return CType(Me(Me.tableDemoOptions.ZDisplacementColumn),Double)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.ZDisplacementColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property XRotation() As Double
            Get
                If Me.IsXRotationNull Then
                    Return 0R
                Else
                    Return CType(Me(Me.tableDemoOptions.XRotationColumn),Double)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.XRotationColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property YRotation() As Double
            Get
                If Me.IsYRotationNull Then
                    Return 0R
                Else
                    Return CType(Me(Me.tableDemoOptions.YRotationColumn),Double)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.YRotationColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ZRotation() As Double
            Get
                If Me.IsZRotationNull Then
                    Return 0R
                Else
                    Return CType(Me(Me.tableDemoOptions.ZRotationColumn),Double)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.ZRotationColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DisplacementUnits() As String
            Get
                If Me.IsDisplacementUnitsNull Then
                    Return ""
                Else
                    Return CType(Me(Me.tableDemoOptions.DisplacementUnitsColumn),String)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.DisplacementUnitsColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property RotationUnits() As String
            Get
                If Me.IsRotationUnitsNull Then
                    Return ""
                Else
                    Return CType(Me(Me.tableDemoOptions.RotationUnitsColumn),String)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.RotationUnitsColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property FirstTimeRunning() As Boolean
            Get
                If Me.IsFirstTimeRunningNull Then
                    Return true
                Else
                    Return CType(Me(Me.tableDemoOptions.FirstTimeRunningColumn),Boolean)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.FirstTimeRunningColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DiagnosticUseThermistor() As Boolean
            Get
                If Me.IsDiagnosticUseThermistorNull Then
                    Return true
                Else
                    Return CType(Me(Me.tableDemoOptions.DiagnosticUseThermistorColumn),Boolean)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.DiagnosticUseThermistorColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ConnectionMode() As String
            Get
                If Me.IsConnectionModeNull Then
                    Return "DIFFERENTIAL"
                Else
                    Return CType(Me(Me.tableDemoOptions.ConnectionModeColumn),String)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.ConnectionModeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PresentationIconFile() As String
            Get
                If Me.IsPresentationIconFileNull Then
                    Return "ATI1.ico"
                Else
                    Return CType(Me(Me.tableDemoOptions.PresentationIconFileColumn),String)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.PresentationIconFileColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PresentationTitle() As String
            Get
                If Me.IsPresentationTitleNull Then
                    Return "ATI F/T Visualizer"
                Else
                    Return CType(Me(Me.tableDemoOptions.PresentationTitleColumn),String)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.PresentationTitleColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PresentationHeading() As String
            Get
                If Me.IsPresentationHeadingNull Then
                    Return "ATI Industrial Automation - Force/Torque Sensors"
                Else
                    Return CType(Me(Me.tableDemoOptions.PresentationHeadingColumn),String)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.PresentationHeadingColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PresentationBannerFile() As String
            Get
                If Me.IsPresentationBannerFileNull Then
                    Return "ATI logo_4c_w_tag.JPG"
                Else
                    Return CType(Me(Me.tableDemoOptions.PresentationBannerFileColumn),String)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.PresentationBannerFileColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property AutoScaleHistory() As Boolean
            Get
                If Me.IsAutoScaleHistoryNull Then
                    Return false
                Else
                    Return CType(Me(Me.tableDemoOptions.AutoScaleHistoryColumn),Boolean)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.AutoScaleHistoryColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property HistoryViewMode() As Boolean
            Get
                If Me.IsHistoryViewModeNull Then
                    Return false
                Else
                    Return CType(Me(Me.tableDemoOptions.HistoryViewModeColumn),Boolean)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.HistoryViewModeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property HistoryDuration() As String
            Get
                If Me.IsHistoryDurationNull Then
                    Return "10"
                Else
                    Return CType(Me(Me.tableDemoOptions.HistoryDurationColumn),String)
                End If
            End Get
            Set
                Me(Me.tableDemoOptions.HistoryDurationColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsCalibrationFileNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.CalibrationFileColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetCalibrationFileNull()
            Me(Me.tableDemoOptions.CalibrationFileColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsDAQDeviceNameNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.DAQDeviceNameColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetDAQDeviceNameNull()
            Me(Me.tableDemoOptions.DAQDeviceNameColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsDAQSampleRateNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.DAQSampleRateColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetDAQSampleRateNull()
            Me(Me.tableDemoOptions.DAQSampleRateColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsAveragingNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.AveragingColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetAveragingNull()
            Me(Me.tableDemoOptions.AveragingColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsDAQFirstChannelNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.DAQFirstChannelColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetDAQFirstChannelNull()
            Me(Me.tableDemoOptions.DAQFirstChannelColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsUseThermistorNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.UseThermistorColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetUseThermistorNull()
            Me(Me.tableDemoOptions.UseThermistorColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsBufferSizeNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.BufferSizeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetBufferSizeNull()
            Me(Me.tableDemoOptions.BufferSizeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsForceUnitsNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.ForceUnitsColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetForceUnitsNull()
            Me(Me.tableDemoOptions.ForceUnitsColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsTorqueUnitsNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.TorqueUnitsColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetTorqueUnitsNull()
            Me(Me.tableDemoOptions.TorqueUnitsColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsDiagnosticSampleRateNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.DiagnosticSampleRateColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetDiagnosticSampleRateNull()
            Me(Me.tableDemoOptions.DiagnosticSampleRateColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsDiagnosticSampleSizeNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.DiagnosticSampleSizeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetDiagnosticSampleSizeNull()
            Me(Me.tableDemoOptions.DiagnosticSampleSizeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsDiagnosticAveragingNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.DiagnosticAveragingColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetDiagnosticAveragingNull()
            Me(Me.tableDemoOptions.DiagnosticAveragingColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsXDisplacementNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.XDisplacementColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetXDisplacementNull()
            Me(Me.tableDemoOptions.XDisplacementColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsYDisplacementNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.YDisplacementColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetYDisplacementNull()
            Me(Me.tableDemoOptions.YDisplacementColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsZDisplacementNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.ZDisplacementColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetZDisplacementNull()
            Me(Me.tableDemoOptions.ZDisplacementColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsXRotationNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.XRotationColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetXRotationNull()
            Me(Me.tableDemoOptions.XRotationColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsYRotationNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.YRotationColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetYRotationNull()
            Me(Me.tableDemoOptions.YRotationColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsZRotationNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.ZRotationColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetZRotationNull()
            Me(Me.tableDemoOptions.ZRotationColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsDisplacementUnitsNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.DisplacementUnitsColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetDisplacementUnitsNull()
            Me(Me.tableDemoOptions.DisplacementUnitsColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsRotationUnitsNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.RotationUnitsColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetRotationUnitsNull()
            Me(Me.tableDemoOptions.RotationUnitsColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsFirstTimeRunningNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.FirstTimeRunningColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetFirstTimeRunningNull()
            Me(Me.tableDemoOptions.FirstTimeRunningColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsDiagnosticUseThermistorNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.DiagnosticUseThermistorColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetDiagnosticUseThermistorNull()
            Me(Me.tableDemoOptions.DiagnosticUseThermistorColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsConnectionModeNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.ConnectionModeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetConnectionModeNull()
            Me(Me.tableDemoOptions.ConnectionModeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsPresentationIconFileNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.PresentationIconFileColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetPresentationIconFileNull()
            Me(Me.tableDemoOptions.PresentationIconFileColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsPresentationTitleNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.PresentationTitleColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetPresentationTitleNull()
            Me(Me.tableDemoOptions.PresentationTitleColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsPresentationHeadingNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.PresentationHeadingColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetPresentationHeadingNull()
            Me(Me.tableDemoOptions.PresentationHeadingColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsPresentationBannerFileNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.PresentationBannerFileColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetPresentationBannerFileNull()
            Me(Me.tableDemoOptions.PresentationBannerFileColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsAutoScaleHistoryNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.AutoScaleHistoryColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetAutoScaleHistoryNull()
            Me(Me.tableDemoOptions.AutoScaleHistoryColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsHistoryViewModeNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.HistoryViewModeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetHistoryViewModeNull()
            Me(Me.tableDemoOptions.HistoryViewModeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsHistoryDurationNull() As Boolean
            Return Me.IsNull(Me.tableDemoOptions.HistoryDurationColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetHistoryDurationNull()
            Me(Me.tableDemoOptions.HistoryDurationColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Class DemoOptionsRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As DemoOptionsRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New(ByVal row As DemoOptionsRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Row() As DemoOptionsRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
